Fix Client Process Function
commercetools/commercetools-sdk-typescript pull request #637
Opened 2024-03-13 09:46 UTC by ajimae

### Summary
Fix Client Process Function

### Tasks Completed
- [x] fix static limit for the process fn options
- [x] remove old implementations to use limit from options

2024-03-15 09:15 UTC, lojzatran requested changes
In the JIRA task you wrote that `sort` has hardcoded value, but here sort is not changed anywhere. And in the github issue the cusomer was reporting an error related to expansion and this is also not addressed here. Can you explain why?

2024-03-15 09:15 UTC, lojzatran commented on packages/sdk-client/src/sdk-client/client.ts
> +    let hasFirstPageBeenProcessed = false
Why this change?

2024-03-15 09:15 UTC, lojzatran commented on packages/sdk-client/src/utils/index.ts
> +export const PAGE_LIMIT = 20;
It‘s better to keep this in `client.ts` file since it‘s used only there.

2024-03-15 09:15 UTC, lojzatran commented on packages/sdk-client/test/client.test/sdk-client.test.ts
>  import fetch from 'node-fetch'
Please add a test that proves your fix is actually working - a test that fails on master branch but passes on your branch.

2024-03-18 15:16 UTC, ajimae commented
> In the JIRA task you wrote that `sort` has hardcoded value, but here sort is not changed anywhere. And in the github issue the cusomer was reporting an error related to expansion and this is also not addressed here. Can you explain why?

This is obviously a mistake. I have corrected the JIRA task.

2024-03-18 21:20 UTC, lojzatran approved these changes
Good job! 👍

2024-03-18 21:20 UTC, lojzatran commented on packages/platform-sdk/test/integration-tests/process/process.test.ts
> +      .then((response) => {
It‘s better to use await here since you defined already the async function.

2024-03-19 23:19 UTC, merged